name: fitness_social_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Local Assets Configuration
  assets:
    # Profile Images
    - assets/images/profiles/
    - assets/images/profiles/profile_1.jpg
    - assets/images/profiles/profile_2.jpg
    - assets/images/profiles/profile_female_1.jpg
    - assets/images/profiles/profile_male_1.jpg
    - assets/images/profiles/default_profile.png
    
    # Workout Post Images
    - assets/images/posts/
    - assets/images/posts/workout_deadlift.jpg
    - assets/images/posts/workout_bench.jpg
    - assets/images/posts/workout_squats.jpg
    - assets/images/posts/workout_dumbbells.jpg
    - assets/images/posts/workout_cardio.jpg
    - assets/images/posts/workout_yoga.jpg
    - assets/images/posts/workout_pushups.jpg
    - assets/images/posts/workout_stretching.jpg
    
    # Nutrition Post Images
    - assets/images/posts/nutrition_mealprep.jpg
    - assets/images/posts/nutrition_bowl.jpg
    - assets/images/posts/nutrition_shake.jpg
    - assets/images/posts/nutrition_salad.jpg
    
    # Progress Photos
    - assets/images/progress/
    - assets/images/progress/progress_before_1.jpg
    - assets/images/progress/progress_after_1.jpg
    - assets/images/progress/progress_before_2.jpg
    - assets/images/progress/progress_after_2.jpg
    
    # Branding Assets
    - assets/images/branding/
    - assets/images/branding/app_logo.png
    - assets/images/branding/thrivespace_logo.png
    - assets/images/branding/splash_background.jpg
    
    # Coach Profiles
    - assets/images/coaches/
    - assets/images/coaches/coach_mike.jpg
    - assets/images/coaches/coach_anna.jpg
    - assets/images/coaches/coach_john.jpg
    
    # Placeholders
    - assets/placeholders/
    
    # Icons
    - assets/icons/